### ISSUE TITLE
LogCopier uses too much CPU

### ISSUE THREAD

**Issue by kadaan** [linkedin/gobblin#729] opened 2016-02-19 19:09 UTC
We are running Gobblin on yarn with 5 nodes and 49 containers, resulting in 98 files to copy.  The LogCopier on the driver ends up running constantly and making the machine run at 50%+ cpu usage.

**Comment by kadaan** [comment] 2016-02-19 19:23
<img width="500" alt="screen shot 2016-02-19 at 10 59 37 am" src="https://cloud.githubusercontent.com/assets/1904898/13186442/148d47c6-d6fb-11e5-9900-aa1907ce83d9.png">
<img width="500" alt="screen shot 2016-02-19 at 11 03 59 am" src="https://cloud.githubusercontent.com/assets/1904898/13186445/16903952-d6fb-11e5-944f-3b4e553c8ce1.png">
<img width="500" alt="screen shot 2016-02-19 at 11 05 22 am" src="https://cloud.githubusercontent.com/assets/1904898/13186446/1a9173cc-d6fb-11e5-9999-3eb3c5eccac7.png">

**Comment by sahilTakiar** [comment] 2016-02-24 00:59
* What tool are you using to generate these images?
* There doesn't seem to be a config parameter to control the sync interval, which is 2 minutes by default. 2 minutes seems pretty long so not sure this is the issue
* The `LogCopier` reads each line in the log file into a `String` and then writes it to the destination, it may be more efficient to just do a raw byte level copy
    * It does this so it can apply an optional regex to each line to exclude certain patterns, however, this feature does not seem to be used so I'm not sure its needed
* The copier uses `FileSystem.append` don't have much experience with this function but I wonder how efficient it is

Nothing else looks out of the ordinary in the code base. Will need to dig deeper.

**Comment by kadaan** [comment] 2016-02-24 01:58
@sahilTakiar This was captured using YourKit. The majority of the time is taken in the ScheduledThreadPoolExecutor. I replaced it with HashedWheelTimer and the performance is way better. I will try to reproduce again and add more details. What else would you like to know?

**Comment by kadaan** [comment] 2016-02-25 08:28
I'm going to submit a PR with the ability to switch between two different scheduler: ScheduledThreadPoolExecutor and HashedWheelTimer.

**Comment by sahilTakiar** [comment] 2016-02-25 17:40
Thanks for the info. So based on the YourKit analysis, the issue is with `ScheduledThreadPoolExecutor.getTask()` taking up a lot of CPU, is that correct? If so I agree replacing it something more efficient makes sense. Is the `HashedWheelTimer` you are referring to the one from Netty?

Is the change you plan to make going to control all current uses of `ScheduledThreadPoolExecutor`, or just the one in `LogCopier`?

**Comment by kadaan** [comment] 2016-02-25 17:46
@sahilTakiar,

1. Yes, that is what it seemed like
2. It is the HashedWheelTimer from netty.  
3. I plan on creating the following in utils/concurrent:

```java
public interface ScheduledTask<K> {
    K getKey();
    void run();
}
public interface CancellableScheduledTask<K> extends ScheduledTask<K> {
    void cancel();
}
public abstract class TaskScheduler<K, T extends ScheduledTask<K>> implements Closeable {
  private final Multimap<K, CancellableScheduledTask<K>> cancellableScheduleTaskMap = ArrayListMultimap.create();

  public final void schedule(T task, long interval, TimeUnit timeUnit) {
    CancellableScheduledTask<K> cancellable = scheduleImpl(task, interval, timeUnit);
    this.cancellableScheduleTaskMap.put(task.getKey(), cancellable);
  }
  public final Iterable<CancellableScheduledTask<K>> getScheduledTasks() {
    return ImmutableList.copyOf(this.cancellableScheduleTaskMap.values());
  }
  public final Iterable<CancellableScheduledTask<K>> getScheduledTasks(K key) {
    return ImmutableList.copyOf(this.cancellableScheduleTaskMap.get(key));
  }

  abstract CancellableScheduledTask<K> scheduleImpl(T task, long interval, TimeUnit timeUnit);
}
```

There will be two concrete implementations: ScheduledThreadPoolExecutor and HashedWheelTimer.  For now, I'm only going to replace the usage in LogCopier.  I'm going to add a config option to switch between the two implementations which will default to ScheduledThreadPoolExecutor.

**Comment by sahilTakiar** [comment] 2016-02-25 18:21
I think we could just remove `ScheduledThreadPoolExecutor` from the `LogCopier` and just use `HashedWheelTimer`; this will save some effort and avoid introducing another config option. From the Netty docs, `HashedWheelTimer` does seem to be more efficient: http://netty.io/wiki/using-as-a-generic-library.html#wiki-h3-12 although I haven't researched it extensively.

@ibuenros any thoughts on this?

**Comment by ibuenros** [comment] 2016-02-25 18:34
It sounds good to me. I don't know much about `ScheduledThreadPoolExecutor` vs `HashedWheelTimer`, are there any advantages to the former? I am fine with completely removing `ScheduledThreadPoolExecutor` if it has no advantages.

I also like the `TaskScheduler` suggested by @kadaan.

**Comment by kadaan** [comment] 2016-02-25 20:21
I think I'm still going to go with my plan for now.  It will let me get done in a backwards compatible way.  As soon as we are comfortable with the HashedWheelTimer version we can make it the default.  Then later, we can delete the ScheduledThreadPoolExecutor version.

**Comment by sahilTakiar** [comment] 2016-03-15 01:21
@kadaan can we close this now?

**Closed** 2016-03-15 01:21 UTC
Labels: enhancement, LaunchType:yarn
