### ISSUE TITLE
Gradle building failed

### ISSUE THREAD

**Issue by darionyaphet** [linkedin/gobblin#618] opened 2016-01-20 04:37 UTC
I'm building `gobblin` with `/gradlew  clean build --debug` .
This  java version is "1.8.0_65"  and it's looks like something miss when running git command ?

```
12:25:25.203 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
12:25:25.204 [ERROR] [org.gradle.BuildExceptionReporter]
12:25:25.204 [ERROR] [org.gradle.BuildExceptionReporter] * Where:
12:25:25.205 [ERROR] [org.gradle.BuildExceptionReporter] Build file '/Users/MLS/source/gobblin-gobblin_0.6.0/build.gradle' line: 62
12:25:25.205 [ERROR] [org.gradle.BuildExceptionReporter]
12:25:25.205 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
12:25:25.206 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred evaluating root project 'gobblin-gobblin_0.6.0'.
12:25:25.206 [ERROR] [org.gradle.BuildExceptionReporter] > Process 'command 'git'' finished with non-zero exit value 128
```

**Comment by sahilTakiar** [comment] 2016-01-20 17:56
Is `git` installed on the machine you are building on? Can you run the following commands on the same machine and see what the output is: `git fetch -t https://github.com/linkedin/gobblin.git master` `git describe --tags --always`.

**Comment by darionyaphet** [comment] 2016-01-21 03:11
I  checkout gobblin from master and running this command 

```
λ ~/source/gobblin/ master git fetch -t https://github.com/linkedin/gobblin.git master
From https://github.com/linkedin/gobblin
 * branch            master     -> FETCH_HEAD
```
```
λ ~/source/gobblin/ master git describe --tags --always
gobblin_0.6.0-213-g47177c0
```

It seems OK ?

**Comment by sahilTakiar** [comment] 2016-01-22 20:51
Yeah that seems ok. I'm not 100% sure what the root cause is, but as a workaround you run the following command: `./gradlew clean build -Pversion=gobblin_0.6.0-213-g47177c0 -x test`

**Comment by sahilTakiar** [comment] 2016-02-12 23:50
Closing, please re-open if there are more questions.

**Closed by sahilTakiar** 2016-02-12 23:50 UTC
Labels: build
